### ISSUE TITLE
[meta] Remaining dEQP-VK.image failures on Metal

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#2027]
With #2025 and earlier PRs in place, we appear to be a in sight for complete coverage of the "image" category of tests. Current stats on OSX:
  - success: 2009
  - failure: 3 (! all located in `image.qualifiers`, may be intermittent due to #1984)
  - crash: 1378

Crash cases:
- [ ]  "dEQP-VK.image.store.with_format.cube_array.r8g8b8a8_unorm"
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationFailed("Compilation failed: \n\nprogram_source:11:263: error: vector component access exceeds type \'int3\' (aka \'vector_int3\')\n    _31.write(float4(float((_8 ^ _18) ^ _23), float(((63 - _8) ^ _18) ^ _23), float((_8 ^ (63 - _18)) ^ _23), float(((63 - _8) ^ (63 - _18)) ^ _23)) * 0.01587300002574920654296875, uint2(int3(_8, _18, _23).xy), uint(int3(_8, _18, _23).z), uint(int3(_8, _18, _23).w));\n                                                                                                                                                                                                                                                                      ^~\n")', libcore/result.rs:945:5

- [ ] "dEQP-VK.image.store.with_format.buffer.r32g32b32a32_sfloat"
> validateComputeFunctionArguments:860: failed assertion `Compute Function(main0): writes texture (_31[0]) whose usage (0x01) doesn't specify MTLTextureUsageShaderWrite (0x02)'

-  [ ] "dEQP-VK.image.mutable.2d_array.r32g32b32a32_sfloat_r32g32b32a32_uint_draw_texture"
> thread '<unnamed>' panicked at 'not yet implemented', /Users/dmalyshau/Code/gfx/src/backend/metal/src/command.rs:1723:9
     
-  [ ] "dEQP-VK.image.image_size.*"
> validateComputeFunctionArguments:820: failed assertion `Compute Function(main0): argument _10[0] from buffer(0) with offset(0) and length(12) has space for 12 bytes, but argument has a length(16).'

-  [ ] "dEQP-VK.image.atomic_operations.min.cube_array.r32i_intermediate_values"
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationFailed("Compilation failed: \n\nprogram_source:14:72: warning: expression result unused\n    int _57 = atomic_fetch_min_explicit((volatile device atomic_int*)&(_37, int3(_8 % 64, _18, _23)), ((_8 * _8) + (_18 * _18)) + (_23 * _23), memory_order_relaxed);\n                                                                       ^~~\nprogram_source:14:70: error: cannot take the address of an rvalue of type \'int3\' (aka \'vector_int3\')\n    int _57 = atomic_fetch_min_explicit((volatile device atomic_int*)&(_37, int3(_8 % 64, _18, _23)), ((_8 * _8) + (_18 * _18)) + (_23 * _23), memory_order_relaxed);\n                                                                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~\nprogram_source:15:107: error: vector component access exceeds type \'int3\' (aka \'vector_int3\')\n    _30.write(int4(_57), uint2(int3(_8, _18, _23).xy), uint(int3(_8, _18, _23).z), uint(int3(_8, _18, _23).w));\n                                                                                                          ^~\n")',

**Comment by grovesNL** [comment]
Created KhronosGroup/SPIRV-Cross#578 for `dEQP-VK.image.store.with_format.cube_array.r8g8b8a8_unorm`

**Comment by grovesNL** [comment]
`dEQP-VK.image.store.with_format.buffer.r32g32b32a32_sfloat` seems to pass now, if you could confirm
